FROM ubuntu:20.04

WORKDIR /app

RUN apt-get update

RUN DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC apt install -y tzdata

RUN apt-get upgrade

RUN apt-get install -y python3.9 \
    python3-pip \
    git \
    wget \
    libgl1-mesa-glx \
    libglib2.0-0 

EXPOSE 80

COPY FastAPI_backend/requirements.txt .

RUN pip install -r requirements.txt

RUN apt-get install -y 

COPY FastAPI_backend/ ./FastAPI_backend/

RUN git clone https://github.com/arsfutura/face-recognition.git

RUN cp -r face-recognition/face_recognition FastAPI_backend/

RUN rm -r face-recognition

CMD python3 FastAPI_backend/main.py -p 80
