name: Python Lint flake mypy and isort

on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:

jobs:
  pi_checks:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Check if changed files include python files
      uses: technote-space/get-diff-action@v6
      with:
        DIFF_FILTER: 'ACDMRTUXB' # https://git-scm.com/docs/git-diff
        PATTERNS: |
          **.py
          **/*.py
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install types-requests types-aiofiles types-PyYAML types-redis
        pip install flake8 mypy isort==5.12.0 pytest numpy==1.24.4 opencv_python==4.8.0.76

    - name: Lint with flake8
      run: |
        # E402: module level import not at top of file
        flake8 pi_cam/ --count --statistics --ignore=E402 --max-line-length 120

    - name: Type checking with mypy
      run: |
        mypy pi_cam/ --ignore-missing-imports
    - name: Sort check with isort
      run: |
        isort pi_cam/ --diff
        isort pi_cam/ --check-only
    - name: Unittest with pytest
      run: |
        pytest tests/pi_test.py

  cloud_checks:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Check if changed files include python files
      uses: technote-space/get-diff-action@v6
      with:
        DIFF_FILTER: 'ACDMRTUXB' # https://git-scm.com/docs/git-diff
        PATTERNS: |
          **.py
          **/*.py
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install types-requests types-aiofiles types-PyYAML types-redis
        pip install flake8 mypy isort==5.12.0 pytest pillow joblib==1.3.2

    - name: Lint with flake8
      run: |
        # E402: module level import not at top of file
        flake8 FastAPI_backend/ --count --statistics --ignore=E402 --max-line-length 120

    - name: Type checking with mypy
      run: |
        mypy FastAPI_backend/ --ignore-missing-imports
    - name: Sort check with isort
      run: |
        isort FastAPI_backend/ --diff
        isort FastAPI_backend/ --check-only
    - name: Unittest with pytest
      run: |
        pytest tests/fastapi_test.py
